### ISSUE TITLE
Breaks in Gulp 4, adds leading slash

### ISSUE THREAD

**Issue by damonmaria** [jussi-kalliokoski/gulp-awspublish-router#19]
I think a change in Vinyl has broken this package. `file.base` will not have a trailing slash according to the [Vinyl docs](https://www.npmjs.com/package/vinyl). Therefore this line in `initFile.js`:

`file.s3.path = file.path.replace(file.base, "").replace(new RegExp("\\" + path.sep, "g"), "/")`

Will end up with a leading slash. Which then causes all files in S3 to be put into a top level 'directory' with no name.

**Comment by jussi-kalliokoski** [comment]
Thanks for reporting *and* debugging! :heart: :tada:

Fixed in https://github.com/jussi-kalliokoski/gulp-awspublish-router/commit/a8fc995349ff2ad710b07e121053d0abb4981515 and released as [v0.1.4](https://github.com/jussi-kalliokoski/gulp-awspublish-router/commit/d46eb677f464c3fec7f3a8fd0d02d143cc0f113f).
